name: jobs

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to use
        required: true

defaults:
  run:
    shell: bash

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - run: npm i -g serve
      - run: which serve

  deps:
    runs-on: ubuntu-20.04
    steps:
      - run: which serve
