name: release

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to use
        required: true

defaults:
  run:
    shell: bash

jobs:
  cache-warmer:
    timeout-minutes: 30

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - uses: ahmadnassri/action-github-registry-npm-proxy@v2.1
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN_READ }}
          scope: ${{ github.repository_owner }}
          path: ${{ github.workspace }}/.npmrc
          export_user_config: true

      - run: |
          mkdir -p ~/.npm/packages
          mkdir -p ~/.npm/cache
          npm config set prefix ~/.npm/packages
          npm config set cache ~/.npm/cache
          echo "$(npm --global bin)" >> $GITHUB_PATH
          npm config get prefix

      - uses: actions/cache@v2.1.4
        with:
          key: ${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
            ~/.turtle
            ~/.gradle/wrapper
            node_modules

      - name: Install dependencies
        run: |
          npm install --global turtle-cli expo-cli
          npm ci


  release:
    needs: [ cache-warmer ]

    timeout-minutes: 5

    runs-on: ubuntu-20.04

    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1

      - uses: ahmadnassri/action-workflow-queue@v1

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - uses: ahmadnassri/action-npm-global-path@v1
        with:
          path: ~/.npm

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: ahmadnassri/action-github-registry-npm-proxy@v2
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN_READ }}
          path: ${{ github.workspace }}/.npmrc
          export_user_config: true

      - run: |
          npm config get prefix
          mkdir -p ~/.npm/packages
          mkdir -p ~/.npm/cache
          npm config set prefix ~/.npm/packages
          npm config set cache ~/.npm/cache
          echo "$(npm --global bin)" >> $GITHUB_PATH
          npm config get prefix

      - uses: actions/cache@v2.1.4
        with:
          key: ${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
            node_modules

      - uses: ahmadnassri/action-semantic-release@v1
        id: release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }} # use repo-specific token
          GITHUB_TOKEN: ${{ secrets.GH_ORG_TOKEN_WRITE }} # use special token to trigger follow-up actions

